Resize GENIE Graph and Update README
GenomicMedLab/variation-normalizer-manuscript pull request #107
Opened 2024-01-10 21:01 UTC by jarbesfeld

Closes #106 

Resize GENIE graph and include updated graph on README.

2024-01-10 21:03 UTC, jarbesfeld commented
Will resolve merge conflicts first

2024-01-15 13:45 UTC, korikuzma requested changes

2024-01-15 14:24 UTC, korikuzma approved these changes

2024-01-15 14:27 UTC, korikuzma commented
@jarbesfeld there are conflicts. Can you resolve?

2024-01-15 14:29 UTC, jarbesfeld commented
@korikuzma I realized I haven't resolved merge conflicts yet on the command line. Should I just follow the instructions here:
<img width="796" alt="Screenshot 2024-01-15 at 9 29 10 AM" src="https://github.com/GenomicMedLab/variation-normalizer-manuscript/assets/50678786/48feb226-4677-431b-ab3e-32845d5b1e67">

2024-01-15 14:30 UTC, korikuzma commented
@jarbesfeld yes

2024-01-15 14:34 UTC, jarbesfeld commented
@korikuzma Step 3 failed when I tried `git merge main`
rsjxa001@RESWCL4QK7DJL variation-normalizer-manuscript % git merge main
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
warning: Cannot merge binary files: analysis/genie/variant_analysis/genie_patient_matching.png (HEAD vs. main)
Auto-merging analysis/genie/variant_analysis/genie_patient_matching.png
CONFLICT (add/add): Merge conflict in analysis/genie/variant_analysis/genie_patient_matching.png
Auto-merging analysis/genie/variant_analysis/genie_search_analysis.ipynb
CONFLICT (content): Merge conflict in analysis/genie/variant_analysis/genie_search_analysis.ipynb
Automatic merge failed; fix conflicts and then commit the result.
Should I resolve the merge conflicts before this step?

2024-01-15 14:35 UTC, korikuzma commented
@jarbesfeld yes

2024-01-15 15:26 UTC, korikuzma requested changes

2024-01-15 15:26 UTC, korikuzma commented on analysis/download_s3_files.ipynb
You shouldn't be making any changes to this. Revert this file to this commit ea62142 by doing the following:

`git checkout ea62142 analysis/download_s3_files.ipynb`

2024-01-15 15:31 UTC, wesleygoar approved these changes

2024-01-15 15:36 UTC, korikuzma approved these changes

2024-01-15 15:38 UTC, merged